apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiYXV0aHMiOiB7CgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIlRYbDZibWxyYjNaQlVEcG5hSEJmTm5kMFVFbzFkSGczYTB4eFoyVm9lWEV6YVRaeGRHa3hlRlZYTTFOMk1sSlRZbXRpIgogICAgICAgIH0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
